version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:$ELK_VERSION
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ELASTIC_PASSWORD=W1QqYDqf7gxwuCqfTS8l"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - $PWD/elasticsearch/data:/usr/share/elasticsearch/data
      - $PWD/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - wise_sfbd_net

  logstash:
    image: logstash:$ELK_VERSION
    container_name: logstash
    hostname: logstash
    volumes:
      - $PWD/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - $PWD/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - wise_sfbd_net
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:$ELK_VERSION
    container_name: kibana
    hostname: kibana
    volumes:
      - $PWD/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - wise_sfbd_net
    depends_on:
      - elasticsearch

networks:
  wise_sfbd_net:
    external: true
